### ISSUE TITLE
organization teams and ownership

### ISSUE THREAD

**Issue by mfrasca** [Bauble/bauble.github.io#1]
Hi @brettatoms 
can you put me in the Owners team for Bauble?
https://github.com/orgs/Bauble/teams
I need to put some files in the bauble.io site (for distributing packages).

**Comment by brettatoms** [comment]
I took down the bauble.io site a little while back.  It has been redirecting to https://github.com/Bauble/bauble.classic for several months.

**Comment by mfrasca** [comment]
yes, I know that, but this only affects the `index.html`, which holds the redirect.

```
<meta http-equiv="refresh" content="0;URL=https://github.com/Bauble/bauble.classic">
```

I can still use the site (the site still exists) for holding packages.
possibly also screenshots.

I cannot _join_ the Bauble organization, I need an owner to add me.

**Comment by mfrasca** [comment]
thanks! :+1:
